# -----------------------------------------------------------
# ЭТАП 1: СБОРКА (BUILD STAGE)
# -----------------------------------------------------------
FROM node:20-alpine AS build
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем ВЕСЬ код фронтенда в рабочую директорию /app
# Поскольку контекст сборки - это папка lambda-app, 
# эта команда копирует все файлы (включая package.json, src и т.д.)
COPY . . 

# Устанавливаем зависимости reproducible-способом по package-lock.json
ENV PUPPETEER_SKIP_DOWNLOAD=true
RUN npm ci

# Запускаем сборку React-приложения. 
RUN npm run build 

# -----------------------------------------------------------
# ЭТАП 2: ПРОДАКШЕН (PRODUCTION STAGE)
# -----------------------------------------------------------
FROM nginx:alpine AS production

# Удаляем дефолтный конфиг NGINX
RUN rm /etc/nginx/conf.d/default.conf

# КОПИРУЕМ СТАТИЧЕСКИЕ ФАЙЛЫ
# Папка 'build' - это стандартный результат сборки React-scripts
COPY --from=build /app/build /usr/share/nginx/html
