version: '3.8'

services:
  # 1. СЕРВИС БАЗЫ ДАННЫХ (PostgreSQL)
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
      POSTGRES_DB: ${POSTGRES_DB:-lambdadb}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # 2. СЕРВИС БЭКЕНДА (ASP.NET Core API)
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./backend/LambdaGeneration.API/LambdaGeneration.API/Dockerfile
    ports:
      - "8080:8080"
    # КРИТИЧЕСКОЕ ИСПРАВЛЕНИЕ: Чтение ВСЕХ переменных из .env
    env_file:
      - .env

    environment:
      ConnectionStrings__LambdaGenerationDatabase: Host=postgres;Port=5432;Database=db;Username=postgres;Password=123
      # Настройки JWT
      JwtOptions__SecretKey: ${JWTOPTIONS__SECRETKEY}
      JwtOptions__Issuer: ${JWTOPTIONS__ISSUER}
      JwtOptions__Audience: ${JWTOPTIONS__AUDIENCE}
      JwtOptions__ExpiresHours: ${JWTOPTIONS__EXPIRESHOURS}

      # Настройки АДМИНА
      AdminConfig__Name: ${ADMINCONFIG__NAME}
      AdminConfig__Email: ${ADMINCONFIG__EMAIL}
      AdminConfig__Password: ${ADMINCONFIG__PASSWORD}

      # GigaChat
      GigaChat__ClientId: ${GigaChat__ClientId}
      GigaChat__ClientSecret: ${GigaChat__ClientSecret}
      GigaChat__Scope: ${GigaChat__Scope}
      # Email
      EmailSettings__Host: ${EMAILSETTINGS__HOST}
      EmailSettings__Port: ${EMAILSETTINGS__PORT}
      EmailSettings__Username: ${EMAILSETTINGS__USERNAME}
      EmailSettings__Password: ${EMAILSETTINGS__PASSWORD}
      EmailSettings__FromEmail: ${EMAILSETTINGS__FROMEMAIL}
      EmailSettings__FromName: ${EMAILSETTINGS__FROMNAME}
      EmailSettings__EnableSsl: ${EMAILSETTINGS__ENABLESSL}

      # URL клиента
      ClientUrl: ${CLIENTURL}

    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  # 3. СЕРВИС ФРОНТЕНДА (React Build + Nginx)
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "8088:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: always

volumes:
  postgres_data: