services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
      POSTGRES_DB: ${POSTGRES_DB:-lambdadb}
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./backend/LambdaGeneration.API/LambdaGeneration.API/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      ConnectionStrings__LambdaGenerationDatabase: "Host=${DB_HOST:-postgres};Port=${DB_PORT:-5432};Database=${POSTGRES_DB:-lambdadb};Username=${POSTGRES_USER:-postgres};Password='${POSTGRES_PASSWORD:-mysecretpassword}'"
      JwtOptions__SecretKey: ${JWTOPTIONS__SECRETKEY}
      JwtOptions__Issuer: ${JWTOPTIONS__ISSUER}
      JwtOptions__Audience: ${JWTOPTIONS__AUDIENCE}
      JwtOptions__ExpiresHours: ${JWTOPTIONS__EXPIRESHOURS}

      AdminConfig__Name: ${ADMINCONFIG__NAME}
      AdminConfig__Email: ${ADMINCONFIG__EMAIL}
      AdminConfig__Password: ${ADMINCONFIG__PASSWORD}

      DrossAdminConfig__Name: ${DROSSADMINCONFIG__NAME}
      DrossAdminConfig__Email: ${DROSSADMINCONFIG__EMAIL}
      DrossAdminConfig__Password: ${DROSSADMINCONFIG__PASSWORD}

      GigaChat__ClientId: ${GIGACHAT__CLIENTID}
      GigaChat__ClientSecret: ${GIGACHAT__CLIENTSECRET}
      GigaChat__Scope: ${GIGACHAT__SCOPE}

      ImageModeration__ApiKey: ${IMAGEMODERATION__APIKEY}
      ImageModeration__BaseUrl: ${IMAGEMODERATION__BASEURL}
      ImageModeration__Model: ${IMAGEMODERATION__MODEL}

      EmailSettings__Host: ${EMAILSETTINGS__HOST}
      EmailSettings__Port: ${EMAILSETTINGS__PORT}
      EmailSettings__Username: ${EMAILSETTINGS__USERNAME}
      EmailSettings__Password: ${EMAILSETTINGS__PASSWORD}
      EmailSettings__FromEmail: ${EMAILSETTINGS__FROMEMAIL}
      EmailSettings__FromName: ${EMAILSETTINGS__FROMNAME}
      EmailSettings__EnableSsl: ${EMAILSETTINGS__ENABLESSL}

      ClientUrl: ${CLIENTURL}

    volumes:
      - ./backend/LambdaGeneration.API/LambdaGeneration.API/wwwroot:/app/wwwroot
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: always

volumes:
  postgres_data:
