version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"  
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Для 16 версии оставляем старый путь
    ports:
      - "5432:5432"
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_api
    environment:
      - ConnectionStrings__LambdaGenerationDatabase=Host=postgres;Port=5432;Database=db;Username=postgres;Password=123
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    depends_on:
      - postgres

volumes:
  postgres-data: